name: Lints

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-typecheck:
    name: Run typecheck
    runs-on: ubuntu-latest

    steps:
      - name: install dependencies
        run: npm i

      - name: runs typecheck
        run: npm run typecheck
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: install dependencies
        run: npm i

      - name: runs lint
        run: npm run lint
